filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /logs/*.log
    fields:
      log_type: springboot
    fields_under_root: true

output.logstash:
  hosts: ["logstash:5044"]

processors:
  - add_host_metadata: ~
  - add_cloud_metadata: ~
